### ISSUE TITLE
Recreate the user list view

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1004]
## TASK
Create the user list view

![For Root Admin and Ps Team 2.0.jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/42455da8-ced9-4f79-bea8-d750bfea870e)

### Sub tasks

- [ ] Add count of users

- [ ] Add pagination like in the Family list

- [ ] See all the columns with the information provided in the design

- [ ] When an user is chosen to be inactive, the person icon should be changed to the light gray color.

- [ ] For the Root Admin and PS Team, the column of Organization should also show below, to what Hub it belongs to.

**Order of users:**
Like the family list, the last user created should be at the top. And there will be an arrow next to the username if someone wants to order it alphabetically.
