### ISSUE TITLE
Create edit modal for Organizations

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#947]
Env: All
Users: Hub admins

## TASK

**Create edit modal**

- [x] Make description field optional and with restriction: 140 characters
- [x] Remove add logo box from front-end and database
- [x] Hide the information field but do not delete from database
