### ISSUE TITLE
Create add organization modal

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#949]
Env: All
Users: Hub admins

## TASK

**Create add organization modal**

- [x] Make description field optional and with restriction: 140 characters
- [x] Remove add logo box from front-end and database
- [x] Hide the information field but do not delete from database
